name: Deploy Docs

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build Docs
        run: |
          xcrun xcodebuild docbuild \
            -scheme ActionKit \
            -destination 'generic/platform=macOS' \
            -derivedDataPath "$PWD/.derivedData" \
            -skipPackagePluginValidation
          xcrun docc process-archive transform-for-static-hosting \
            "$PWD/.derivedData/Build/Products/Debug/ActionKit.doccarchive" \
            --output-path "docs" \
            --hosting-base-path "ActionKit-macOS"
      - name: Modify Docs
        run: |
          echo "<script>window.location.href += \"/documentation/actionkit\"</script>" > docs/index.html;
          sed -i '' 's/,2px/,10px/g' docs/css/index.038e887c.css
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

